# Homework 4 - 3/3/22

## Question 1


In [1]:
#question 1a
import numpy as np

C=np.array([6,-4,27])
C

array([ 6, -4, 27])

In [2]:
#question 1b
C=C.reshape(3,1)
C

array([[ 6],
       [-4],
       [27]])

In [3]:
#question 1c
C[-1]

array([27])

In [4]:
#question 1d
C[1:3]

array([[-4],
       [27]])

In [5]:
#question 1e
C[:-3:-1]

array([[27],
       [-4]])

In [20]:
#question 1f
A=np.array([[1,1,1],[0,2,5],[2,5,-1]])
A


array([[ 1,  1,  1],
       [ 0,  2,  5],
       [ 2,  5, -1]])

In [21]:
#alternate way

Alt=np.array([1,1,1,0,2,5,2,5,-1]).reshape(3,3)
Alt

array([[ 1,  1,  1],
       [ 0,  2,  5],
       [ 2,  5, -1]])

In [22]:
#question 1g
A[1][2]

5

In [8]:
#question 1h
A[:][2]

array([ 2,  5, -1])

In [9]:
#question 1i
A[:,2]

array([ 1,  5, -1])

In [10]:
#question 1j
np.linalg.det(A)

#not singular because determinant =/= 0

-21.0

question 1k

$ 1(x_1)+1(x_2)+1(x_3) =6  $

$ 0(x_1)+2(x_2)+5(x_3) =-4 $

$ 2(x_1)+5(x_2)-1(x_3) =27 $

In [11]:
#question 1l

from numpy.linalg import inv

x=inv(A)@C
x

array([[ 5.],
       [ 3.],
       [-2.]])

In [12]:
#question 1m
#Find the dot product of row 1 of A with the x vector that you solved in step I. 

A[0:1]@x

array([[6.]])

In [13]:
#question 1n
#Find the product of A with the x vector that you solved in step I. 

A@x

array([[ 6.],
       [-4.],
       [27.]])

$$\begin{bmatrix} 1 & 1 & 1 \\ 0 & 2 & 5 \\ 2 & 5 & -1 \end{bmatrix} *\begin{bmatrix} 5 \\ 3 \\ -2 \end{bmatrix}= \begin{bmatrix} 5*1+ & 1*3+ & 1*-2 \\ 0*5+ & 2*3+ & 5*-2 \\ 2*5+ & 5*3+ & -1*-2 \end{bmatrix} = \begin{bmatrix} 6 \\ -4 \\ 27 \end{bmatrix}$$

In [14]:
#question 1p
x.T@A

array([[ 1.,  1., 22.]])

In [15]:
#question 1q

In [16]:
#question 1r

#Find the eigenvalues of A. 

evals,evecs=np.linalg.eig(A)
evals

array([-4.77879032,  0.72601723,  6.05277309])

## Question 2

In year 1,  the yield on 1-year T-bills is 1%, and on 10-year T-bond is 5%. In year 2, 1-year yield becomes 1.5%, and 10-year yield becomes 8.5%. 
1. In year 2, does the market expect future short-term interest rate to rise or fall, compared with year 1? Why? Explain carefully. 
2. Has the probability of a recession risen or decreased?

### question 2a


the market expects short-term interest rates to rise compared to year 1. We know this because the long-term bond interest rate is the average expected interest rate on short term bonds. If the 10 year interest rate is increasing, that means that investors believe that the short-term interest rates will increase in the future.

### question 2b

The probability of a recession has deceased, because rising bond rates signals that the economy is in an expansionary period