# Midterm 2 Practice Problems

<a id='Content'></a>
Table of Contents:
1. [lecture 7 - NumPY](#Numpy)
2. [Lecture 8 - Visualization](#Visual)
3. [Lecture 9 - Randomness](#Random)
4. [Lecture 10 - Pandas](#Panda) # WIP


[Answer Key](#Answer) #WIP

<a id='Numpy'></a>
## Lecture 7 - Numpy

[table of contents](#Content)

<b> Question 1:</b> Rewrite the following function using Dot Products

In [1]:
def get_PV(FP,i,n):
    total = 0
    for j in range(n):
        total = total + FP/(1+i)**(j+1)
    return total

In [2]:
get_PV(126, 0.05, 25)

1775.8370153216385

<b> Question 2</b> Matrices:
Given the following Matrix, find

2a : Find the element on the second row and third column

2b: Find the element on the third row and 1st column

2c: Find the second row

2d: Find the second and third elements in the second row

2f: Transpose the matrix so the rows are now the columns.

In [13]:
mylist = [ [1,2,3],[4,5,6],[7,8,9] ]
x1 = np.array(mylist)

<b> Question 3:</b> Reshape the following matrix:

3a: into a single row

3b: into a single column

3c: into a matrix with 2 rows


In [35]:
mylist = [ [1,2,3,1],[4,5,6,2],[7,8,9,3],[10,11,12,4] ]
x2 = np.array(mylist)


<b> Question 4:</b> 

Creating Matrices:

4a: create two matrices with 2 rows and 2 columns each. Fill the matrices with random numbers. 

4b: find both dot product of the matrices

4c: find the inverse of the Matrices and prove that the inverse worked

4d: find the determinant of the matrices

<b> Question 5:</b> 

solving systems of equations using python


$ 3x + 8y = 5 $ 

$ 4x + 11y = 7 $

<b> Question 6:</b> 

Create a Matrix, and findthe eigenvalues and eigenvectors

<b> Question 7:</b> 

generate 5 evenly distributed numbers between 2 and 13

<b> Question 8:</b> 

create an array of numbers

8a: find the log(x) for every number in the array

8b: find the sin value of every value in the array

8c: find the standard deviation of the array

8d: find the maximum and minimum value in the array

8e: find the mean of the array

8f: add all of the numbers in the array

8g: Sort the numbers in the array from low->high


<a id='Visual'></a>
______________________________________________
## Lecture 8 - Visualization

[table of contents](#Content)

<b> Question 1:</b> Plot the Sin curve. the color of the line should be red, and it should have a dotted line

<b> Question 2:</b> plot the tangent and cosine functions in the same graph.

- make your graph be 10 units high and 10 units wide
- pick two different colors for the two lines
- your line should be 2units thick
- design a legend
- set y axis to display equally spaced ticks between -1 and 1.
- set x axis to display equally spaced ticks between 0 and 6
- create a title for your graph

<b> Question 3:</b> using the following data, create two bar charts



<u>Bar Chart 1:</u>

graph the populations of the 3 different countries


<u>Bar Chart 2</u>

plot the area of land in the 3 countries

--

your bar chart should:
- have appropriately labeled axes
- have appropriate titles

In [36]:
countries = ['CAN','MEX','USA']
populations = [36.7, 129.2, 325.7]
land_area = [3.85, 0.761, 3.79]

for i in pop

<b> Question 4:</b> 

A 10-year coupon bond has a 1000 face value, and a yearly coupon rate of 5 percent. In a graph, plot the relationship between purchasing prices and the implied yields to maturity. Let prices vary from 800 to 1100.

- step 1, solve for the yields for each price
- step 2, plot

<a id='Random'></a>
_____________________________
## Lecture 9 - Randomness

[table of contents](#Content)

<b> Question 1:</b> 

1a: get 10 numbers from a discrite uniform distribution between 0-1

1b: get 12 whole numbers from a discrete uniform distribution between 1 and 100

1c: draw 10 numbers from a standard normal distribution


<b> Question 2:</b> find how many heads you will get from tossing a coin 10 times

2a: calculate the Probability Mass function for 10 coin tosses.

2b: plot a bar chart to display the data

2d: use python to find the probability of getting exactly 2 heads

<b> Question 3:</b> 

The probability that an adult man in the labor force who is unemployed is about 5%. A random sample of 10 men is taken.

3a: Find the probability that

1. all 10 men are unemployed
2. no men are unemployed
3. exactly 2 men are unemployed
4. at least 2 men are unemployed

3b: Plot the PMF for the data


<b> Question 4:</b> 

On average, 12 students visit David during his office hours per week

4a:
- What is the probability that 10 students go to David's office hours next week?
- What is the probability that at least 10 students go to David's office hours next week?
- What is the probability that more than 1 student go to David's office hours on Monday?

4b: simulate this several times, and plot the distribution of the sample mean

<b> Question 5:</b> 

An energy company is looking for fuel additives that might increase gas mileage for cars. Without additives, their cars are known to average 25 mpg (miles per gallons) with a standard deviation of 2.4 mpg. The company now asks whether a particular new additive increases this value. In a study, thirty cars are sent on a road trip. Suppose it turns out that the thirty cars averaged 25.5 mpg with the additive. Can we conclude from this result that the additive is effective?



<a id='Panda'></a>
__________________
## lecture 10 - Pandas

### Not Finished

[table of contents](#Content)

<b> Question 4:</b> 

<a id='Answer'></a>
__________________
## Answer key

### Not Finished

[table of contents](#Content)

## Numpy Questions

In [1]:
import numpy as np

In [2]:

def get_PV2(FP, i, n):
    stream = np.ones((1,n))*FP
    discount = np.array([ 1/(1+i)**(t+1) for t in range(n) ])
    return stream @ discount

get_PV2(126, 0.05, 25)



array([1775.83701532])

In [13]:
#question 2
mylist = [ [1,2,3],[4,5,6],[7,8,9] ]
x2 = np.array(mylist)

print(x2[1,2])
print(x2[2,0])
print(x2[1,:])
print(x2[1, 1:3])
print(x2.T)

6
7
[4 5 6]
[5 6]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [14]:
#Question 3
mylist = [ [1,2,3,1],[4,5,6,2],[7,8,9,3],[10,11,12,4] ]
x2 = np.array(mylist)

In [19]:
print(x2.reshape((1,16)))
print(x2.reshape((16,1)))
print(x2.reshape(2,8))

[[ 1  2  3  1  4  5  6  2  7  8  9  3 10 11 12  4]]
[[ 1]
 [ 2]
 [ 3]
 [ 1]
 [ 4]
 [ 5]
 [ 6]
 [ 2]
 [ 7]
 [ 8]
 [ 9]
 [ 3]
 [10]
 [11]
 [12]
 [ 4]]
[[ 1  2  3  1  4  5  6  2]
 [ 7  8  9  3 10 11 12  4]]


In [50]:
#Question 4
rng = np.random.default_rng()
m1=np.array(rng.integers(1,11,size=4)).reshape((2,2))
m2=np.array(rng.integers(1,11,size=4)).reshape((2,2))
print(np.linalg.inv(m1))
print(m1@np.linalg.inv(m1))



[[-0.22222222  0.33333333]
 [ 0.33333333 -0.33333333]]
[[1. 0.]
 [0. 1.]]


In [51]:
print(np.linalg.inv(m2))
print(m2@np.linalg.inv(m2))

[[-0.25   0.625]
 [ 0.25  -0.375]]
[[1. 0.]
 [0. 1.]]


In [53]:
print(np.linalg.det(m1))
print(np.linalg.det(m2))

-27.0
-15.999999999999991


In [59]:
#Question 5
A = np.array([[3,8],[4,11]])
B = np.array([[5],[7]])

np.linalg.inv(A) @ B


In [63]:
#Question 6
evals,evecs=np.linalg.eig(A)

print(evals)
print(evecs)

[ 0.07179677 13.92820323]
[[-0.9390708  -0.59069049]
 [ 0.34372377 -0.80689822]]


In [86]:
#question 7
A = np.array([[3,4],[11,8]])

print(np.log(A))

print(np.sin(A))

print(np.std(A))

print(np.max(A),np.min(A))

print(np.mean(A))

print(np.sum(A))

print(A)
A.sort()
print(A)

[[1.09861229 1.38629436]
 [2.39789527 2.07944154]]
[[ 0.14112001 -0.7568025 ]
 [-0.99999021  0.98935825]]
3.2015621187164243
11 3
6.5
26
[[ 3  4]
 [11  8]]
[[ 3  4]
 [ 8 11]]
